spring.config.import=optional:file:env.properties
spring.application.name=EnergyRoad
server.port=${PORT}
spring.datasource.url=${PG_DB_URL}
spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}
jwt.secret=${JWT_SECRET}
mailgun.domain=${MAILGUN_DOMAIN}
mailgun.apiKey=${MAILGUN_API_KEY}
founder.email=${FOUNDER_EMAIL}
founder.pwd=${FOUNDER_PWD}
founder.name=${FOUNDER_NAME}
founder.lastname=${FOUNDER_LASTNAME}
#PER PAYPAL
braintree.environment=${BRAINTREE_ENVIROMENT}
braintree.merchantId=${BRAINTREE_MERCHANTID}
braintree.publicKey=${BRAINTREE_PUBLICKEY}
braintree.privateKey=${BRAINTREE_PRIVATEKEY}

